# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lishizheng/Desktop/Code/stub-learning/stub-index

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lishizheng/Desktop/Code/stub-learning/stub-index

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lishizheng/Desktop/Code/stub-learning/stub-index/CMakeFiles /Users/lishizheng/Desktop/Code/stub-learning/stub-index//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lishizheng/Desktop/Code/stub-learning/stub-index/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stub_index_test

# Build rule for target.
stub_index_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stub_index_test
.PHONY : stub_index_test

# fast build rule for target.
stub_index_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/build
.PHONY : stub_index_test/fast

#=============================================================================
# Target rules for targets named debug_parser

# Build rule for target.
debug_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_parser
.PHONY : debug_parser

# fast build rule for target.
debug_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/build
.PHONY : debug_parser/fast

#=============================================================================
# Target rules for targets named simple_test

# Build rule for target.
simple_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_test
.PHONY : simple_test

# fast build rule for target.
simple_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/build
.PHONY : simple_test/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

examples/debug_parser.o: examples/debug_parser.cpp.o
.PHONY : examples/debug_parser.o

# target to build an object file
examples/debug_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/examples/debug_parser.cpp.o
.PHONY : examples/debug_parser.cpp.o

examples/debug_parser.i: examples/debug_parser.cpp.i
.PHONY : examples/debug_parser.i

# target to preprocess a source file
examples/debug_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/examples/debug_parser.cpp.i
.PHONY : examples/debug_parser.cpp.i

examples/debug_parser.s: examples/debug_parser.cpp.s
.PHONY : examples/debug_parser.s

# target to generate assembly for a file
examples/debug_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/examples/debug_parser.cpp.s
.PHONY : examples/debug_parser.cpp.s

examples/demo.o: examples/demo.cpp.o
.PHONY : examples/demo.o

# target to build an object file
examples/demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/examples/demo.cpp.o
.PHONY : examples/demo.cpp.o

examples/demo.i: examples/demo.cpp.i
.PHONY : examples/demo.i

# target to preprocess a source file
examples/demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/examples/demo.cpp.i
.PHONY : examples/demo.cpp.i

examples/demo.s: examples/demo.cpp.s
.PHONY : examples/demo.s

# target to generate assembly for a file
examples/demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/examples/demo.cpp.s
.PHONY : examples/demo.cpp.s

examples/simple_test.o: examples/simple_test.cpp.o
.PHONY : examples/simple_test.o

# target to build an object file
examples/simple_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/examples/simple_test.cpp.o
.PHONY : examples/simple_test.cpp.o

examples/simple_test.i: examples/simple_test.cpp.i
.PHONY : examples/simple_test.i

# target to preprocess a source file
examples/simple_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/examples/simple_test.cpp.i
.PHONY : examples/simple_test.cpp.i

examples/simple_test.s: examples/simple_test.cpp.s
.PHONY : examples/simple_test.s

# target to generate assembly for a file
examples/simple_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/examples/simple_test.cpp.s
.PHONY : examples/simple_test.cpp.s

src/stub_index.o: src/stub_index.cpp.o
.PHONY : src/stub_index.o

# target to build an object file
src/stub_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_index.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_index.cpp.o
.PHONY : src/stub_index.cpp.o

src/stub_index.i: src/stub_index.cpp.i
.PHONY : src/stub_index.i

# target to preprocess a source file
src/stub_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_index.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_index.cpp.i
.PHONY : src/stub_index.cpp.i

src/stub_index.s: src/stub_index.cpp.s
.PHONY : src/stub_index.s

# target to generate assembly for a file
src/stub_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_index.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_index.cpp.s
.PHONY : src/stub_index.cpp.s

src/stub_parser.o: src/stub_parser.cpp.o
.PHONY : src/stub_parser.o

# target to build an object file
src/stub_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_parser.cpp.o
.PHONY : src/stub_parser.cpp.o

src/stub_parser.i: src/stub_parser.cpp.i
.PHONY : src/stub_parser.i

# target to preprocess a source file
src/stub_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_parser.cpp.i
.PHONY : src/stub_parser.cpp.i

src/stub_parser.s: src/stub_parser.cpp.s
.PHONY : src/stub_parser.s

# target to generate assembly for a file
src/stub_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/src/stub_parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_parser.dir/build.make CMakeFiles/debug_parser.dir/src/stub_parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_test.dir/build.make CMakeFiles/simple_test.dir/src/stub_parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/stub_parser.cpp.s
.PHONY : src/stub_parser.cpp.s

test/function_stub_test.o: test/function_stub_test.cpp.o
.PHONY : test/function_stub_test.o

# target to build an object file
test/function_stub_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/function_stub_test.cpp.o
.PHONY : test/function_stub_test.cpp.o

test/function_stub_test.i: test/function_stub_test.cpp.i
.PHONY : test/function_stub_test.i

# target to preprocess a source file
test/function_stub_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/function_stub_test.cpp.i
.PHONY : test/function_stub_test.cpp.i

test/function_stub_test.s: test/function_stub_test.cpp.s
.PHONY : test/function_stub_test.s

# target to generate assembly for a file
test/function_stub_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/function_stub_test.cpp.s
.PHONY : test/function_stub_test.cpp.s

test/parser_test.o: test/parser_test.cpp.o
.PHONY : test/parser_test.o

# target to build an object file
test/parser_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/parser_test.cpp.o
.PHONY : test/parser_test.cpp.o

test/parser_test.i: test/parser_test.cpp.i
.PHONY : test/parser_test.i

# target to preprocess a source file
test/parser_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/parser_test.cpp.i
.PHONY : test/parser_test.cpp.i

test/parser_test.s: test/parser_test.cpp.s
.PHONY : test/parser_test.s

# target to generate assembly for a file
test/parser_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/parser_test.cpp.s
.PHONY : test/parser_test.cpp.s

test/stub_entry_test.o: test/stub_entry_test.cpp.o
.PHONY : test/stub_entry_test.o

# target to build an object file
test/stub_entry_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_entry_test.cpp.o
.PHONY : test/stub_entry_test.cpp.o

test/stub_entry_test.i: test/stub_entry_test.cpp.i
.PHONY : test/stub_entry_test.i

# target to preprocess a source file
test/stub_entry_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_entry_test.cpp.i
.PHONY : test/stub_entry_test.cpp.i

test/stub_entry_test.s: test/stub_entry_test.cpp.s
.PHONY : test/stub_entry_test.s

# target to generate assembly for a file
test/stub_entry_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_entry_test.cpp.s
.PHONY : test/stub_entry_test.cpp.s

test/stub_index_test.o: test/stub_index_test.cpp.o
.PHONY : test/stub_index_test.o

# target to build an object file
test/stub_index_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_index_test.cpp.o
.PHONY : test/stub_index_test.cpp.o

test/stub_index_test.i: test/stub_index_test.cpp.i
.PHONY : test/stub_index_test.i

# target to preprocess a source file
test/stub_index_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_index_test.cpp.i
.PHONY : test/stub_index_test.cpp.i

test/stub_index_test.s: test/stub_index_test.cpp.s
.PHONY : test/stub_index_test.s

# target to generate assembly for a file
test/stub_index_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/stub_index_test.cpp.s
.PHONY : test/stub_index_test.cpp.s

test/variable_stub_test.o: test/variable_stub_test.cpp.o
.PHONY : test/variable_stub_test.o

# target to build an object file
test/variable_stub_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/variable_stub_test.cpp.o
.PHONY : test/variable_stub_test.cpp.o

test/variable_stub_test.i: test/variable_stub_test.cpp.i
.PHONY : test/variable_stub_test.i

# target to preprocess a source file
test/variable_stub_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/variable_stub_test.cpp.i
.PHONY : test/variable_stub_test.cpp.i

test/variable_stub_test.s: test/variable_stub_test.cpp.s
.PHONY : test/variable_stub_test.s

# target to generate assembly for a file
test/variable_stub_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stub_index_test.dir/build.make CMakeFiles/stub_index_test.dir/test/variable_stub_test.cpp.s
.PHONY : test/variable_stub_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... debug_parser"
	@echo "... demo"
	@echo "... simple_test"
	@echo "... stub_index_test"
	@echo "... examples/debug_parser.o"
	@echo "... examples/debug_parser.i"
	@echo "... examples/debug_parser.s"
	@echo "... examples/demo.o"
	@echo "... examples/demo.i"
	@echo "... examples/demo.s"
	@echo "... examples/simple_test.o"
	@echo "... examples/simple_test.i"
	@echo "... examples/simple_test.s"
	@echo "... src/stub_index.o"
	@echo "... src/stub_index.i"
	@echo "... src/stub_index.s"
	@echo "... src/stub_parser.o"
	@echo "... src/stub_parser.i"
	@echo "... src/stub_parser.s"
	@echo "... test/function_stub_test.o"
	@echo "... test/function_stub_test.i"
	@echo "... test/function_stub_test.s"
	@echo "... test/parser_test.o"
	@echo "... test/parser_test.i"
	@echo "... test/parser_test.s"
	@echo "... test/stub_entry_test.o"
	@echo "... test/stub_entry_test.i"
	@echo "... test/stub_entry_test.s"
	@echo "... test/stub_index_test.o"
	@echo "... test/stub_index_test.i"
	@echo "... test/stub_index_test.s"
	@echo "... test/variable_stub_test.o"
	@echo "... test/variable_stub_test.i"
	@echo "... test/variable_stub_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

